#pragma once

enum class TetrisEvents
{
	eTETRIS_EVENT_SPLASH_KEY_PRESSED,
	eTETRIS_EVENT_MENU_START_GAME,
	eTETRIS_EVENT_MENU_SETTINGS,
	eTETRIS_EVENT_MENU_SCORES,
	eTETRIS_EVENT_MENU_QUIT_GAME,
	eTETRIS_EVENT_SAVE_SCORES,
	eTETRIS_EVENT_RESET_SCORES,
	eTETRIS_EVENT_GAME_RETURN_MENU,
	eTETRIS_EVENT_GAME_RECORD_SCORE,
};